[rocky_servers]
# 替换为你的受控节点 IP
rocky10-node01 ansible_host=192.168.112.136

[rocky_servers:vars]
# Rocky 10 默认 Python 路径
ansible_python_interpreter=/usr/bin/python3.12
# 受控用户与权限提升
ansible_user=danny
ansible_become=true
# SSH 优化：重用连接以加速执行
ansible_ssh_extra_args='-o ControlMaster=auto -o ControlPersist=60s'
